# Generated by Django 5.1.5 on 2025-02-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltrainerprofile',
            name='experience',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
