# Generated by Django 5.1.5 on 2025-02-10 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_exercise_workout_workoutsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainerprofile',
            name='role',
            field=models.CharField(default='personal_trainer', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
