# Generated by Django 5.1.5 on 2025-02-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_exercise_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='dummy',
        ),
    ]
