# Generated by Django 5.1.5 on 2025-03-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_workoutsession_user_exercisesession_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='calories_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
