# Generated by Django 5.1.5 on 2025-03-08 13:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_set_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
