# Generated by Django 5.1.5 on 2025-03-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_chatroom_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='calories_burned',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
