# Generated by Django 5.1.5 on 2025-03-16 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_workout_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt', to='backend.personaltrainerprofile'),
        ),
    ]
