# Generated by Django 5.1.5 on 2025-04-11 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_workout_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTrainerScheduledWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_scheduled_workouts', to=settings.AUTH_USER_MODEL)),
                ('pt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arranged_workouts_clients', to=settings.AUTH_USER_MODEL)),
                ('workout_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.workout')),
            ],
        ),
    ]
