# Generated by Django 5.1.5 on 2025-04-26 15:45

import backend.models
import django.contrib.auth.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_workout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=255, validators=[backend.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_category',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('arms', 'Arms'), ('shoulders', 'Shoulders'), ('abs', 'Abdominals')], default='chest', max_length=20),
        ),
        migrations.AlterField(
            model_name='failedloginattempt',
            name='username',
            field=models.CharField(max_length=255, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=255, validators=[backend.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='calories_burned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
