# Generated by Django 5.1.5 on 2025-04-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_alter_chatroom_name_alter_exercise_muscle_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
