# Generated by Django 5.1.5 on 2025-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_personaltrainerprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltrainerprofile',
            name='experience',
            field=models.CharField(blank=True, default='none', max_length=500),
        ),
    ]
