version: "3.8"

services:
  backend:
    # Build the backend from the Dockerfile we just created
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    
    # Container name is optional; helpful for debugging
    container_name: django-backend

    # In development, mount your local code for hot-reload
    volumes:
      - ./backend:/app

    # Map port 8000 on the host to port 8000 in the container
    ports:
      - "8000:8000"

    # If you want to override the default command in the Dockerfile:
    # command: python manage.py runserver 0.0.0.0:8000

    # If you use environment variables, you can pass them in:
   # environment:
      # Add environment values here, i.e.:
      # - DEBUG=1

  frontend:
    # Build the frontend from its Dockerfile
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    
    container_name: react-frontend

    # Same idea: mount your local code for hot-reload
    volumes:
      - ./frontend:/app

    # Vite defaults to port 5173 (or 3000, depending on your config).
    # If you use 5173, change accordingly
    ports:
      - "3000:3000"

    depends_on:
      - backend

    # For environment variables:
    #environment:
      # Add environment values here, i.e.:
      # - REACT_APP_API_URL=http://localhost:8000