version: "3.8"

services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend
    container_name: backend
    # Gunicorn listens on 8000 inside the container
    expose:
      - "8000"
    # No local volumes in production
    # If we need environment variables, we can pass them in here
    # environment:
    #   - DJANGO_SETTINGS_MODULE=myproject.settings.production
    networks:
      - shared

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    # We expose port 3000 for the frontend
    expose:
      - "5173"
    # If we need environment variables, we can pass them in here
    # environment:
    #   - REACT_APP_API_URL=http://localhost:8000
    networks:
      - shared

  # This is the Nginx proxy that will handle SSL termination
  nginx:
    platform: linux/amd64
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "443:443"
      # Optionally "80:80" if you’re redirecting HTTP -> HTTPS
      - "80:80"
      - "8000:8000"
    volumes:
      - ./nginx/ssl/certificate.crt:/etc/ssl/certs/certificate.crt:ro
      - ./nginx/ssl/certificate.key:/etc/ssl/private/certificate.key:ro
    networks:
      - shared

networks:
  shared:
    driver: bridge