services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    # Gunicorn listens on 8000 within the docker network
    expose:
      - "8000"
    # Set up environment variables for production
    # environment:
    #  - DJANGO_SETTINGS_MODULE=backend.settings.production
    networks:
      - shared
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    # We expose port 3000 for the frontend within the docker network
    expose:
      - "3000"
    # If we need environment variables, we can pass them in here
    environment:
      #- BACKEND_API_URL=https://igym.vikingthe.dev/api
      #- VITE_BACKEND_API_URL=https://igym.vikingthe.dev/api
      #- BACKEND_WS_URL=wss://igym.vikingthe.dev/api
      #- VITE_BACKEND_WS_URL=wss://igym.vikingthe.dev/api
      - MODE=production
    networks:
      - shared
    restart: unless-stopped

  # This is the Nginx proxy that will handle SSL termination
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - backend
      - frontend
    # Open ports for HTTPS (and HTTP for redirection to HTTPS). 
    # This will be the only entrance point for the application.
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/ssl/certificate.crt:/etc/ssl/certs/certificate.crt:ro
      - ./nginx/ssl/certificate.key:/etc/ssl/private/certificate.key:ro
    networks:
      - shared
    restart: unless-stopped

networks:
  shared:
    driver: bridge