version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: django-backend-prod
    # Gunicorn listens on 8000 inside the container
    expose:
      - "8000"
    # No local volumes in production
    # If we need environment variables, we can pass them in here
    # environment:
    #   - DJANGO_SETTINGS_MODULE=myproject.settings.production
    networks:
      - production-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: react-frontend-prod
    depends_on:
      - backend
    # We expose port 3000 for the frontend
    expose:
      - "3000"
    # If we need environment variables, we can pass them in here
    # environment:
    #   - REACT_APP_API_URL=http://localhost:8000
    networks:
      - production-network

  # This is the Nginx proxy that will handle SSL termination
  nginx:
    # Points to the folder containing your custom Dockerfile
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx-prod
    depends_on:
      - backend
      - frontend
    ports:
      - "443:443"
      # Optionally "80:80" if you’re redirecting HTTP -> HTTPS
      - "80:80"
    volumes:
      - ./nginx/ssl/certificate.crt:/etc/ssl/certs/certificate.crt:ro
      - ./nginx/ssl/certificate.key:/etc/ssl/private/certificate.key:ro
    networks:
      - production-network

networks:
  production-network:
    driver: bridge