# Generated by Django 5.1.5 on 2025-02-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_personaltrainerprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltrainerprofile',
            name='experience',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
    ]
