# Generated by Django 5.1.5 on 2025-02-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_userprofile_height_alter_userprofile_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
