# Generated by Django 5.1.5 on 2025-03-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_exercise_calories_workoutsession_calories_burned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
