# Generated by Django 5.1.5 on 2025-03-08 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_set_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)]),
        ),
    ]
