# Generated by Django 5.1.5 on 2025-03-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_workoutsession_calories_burned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='calories',
        ),
    ]
