# Generated by Django 5.1.5 on 2025-03-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_scheduledworkout'),
        ('backend', '0024_alter_userprofile_user'),
    ]

    operations = [
    ]
