# Generated by Django 5.1.5 on 2025-03-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_userprofile_personal_trainer'),
        ('backend', '0025_merge_20250318_1426'),
    ]

    operations = [
    ]
