# Generated by Django 5.1.5 on 2025-03-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_merge_20250319_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
