# Generated by Django 5.1.5 on 2025-03-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_workoutsession_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainerprofile',
            name='pt_type',
            field=models.CharField(choices=[('general', 'General Fitness Trainer'), ('strength', 'Strength and Conditioning Trainer'), ('functional', 'Functional Training Coach'), ('bodybuilding', 'Bodybuilding Coach'), ('physio', 'Physical Therapist')], default='general', max_length=20),
        ),
    ]
