# Generated by Django 5.1.5 on 2025-04-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_personaltrainerprofile_pt_type'),
        ('backend', '0029_userprofile_profile_picture'),
    ]

    operations = [
    ]
