# Generated by Django 5.1.5 on 2025-04-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
