# Generated by Django 5.1.5 on 2025-04-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_workoutsession_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_category',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('arms', 'Arms'), ('shoulders', 'Shoulders'), ('abs', 'Abdomonals')], default='chest', max_length=20),
        ),
    ]
