# Generated by Django 5.1.5 on 2025-04-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_personaltrainerscheduledworkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
